"""empty message

Revision ID: 66785006c667
Revises: dac424c8ce67
Create Date: 2021-08-30 00:57:42.223309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66785006c667'
down_revision = 'dac424c8ce67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('completed', sa.Boolean(), nullable=True))

    op.execute('UPDATE todos SET completed = False WHERE completed IS NULL;')
    op.alter_column('todos', 'completed', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'completed')
    # ### end Alembic commands ###
